# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'src/server/db/schema/**/*'

pool:
  vmImage: ubuntu-latest

variables:
- name: npm_config_cache
  value: $(Pipeline.Workspace)/.npm

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '24.x'
  displayName: 'Install Node.js'

- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
    path: $(npm_config_cache)
  displayName: Cache npm

- script: |
    npm ci
    npm run db:dbml
  displayName: 'npm install and db:dbml'

- script: |
    npx @softwaretechnik/dbml-renderer -i schema.dbml -o schema.svg
  displayName: 'Render SVG'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/schema.svg'
    artifactName: 'DatabaseSchema'
    publishLocation: 'pipeline'
    displayName: 'Publish DBML Schema'