trigger: none

schedules:
  - cron: '0 0 * * 1'
    displayName: Audit main branch weekly
    branches:
      include:
        - main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm audit || echo "Issues found in dependencies!"
  displayName: 'npm audit'
