# fly.toml app configuration file generated for odysseat-1 on 2025-08-31T19:21:50+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'odysseat'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = "512mb"
