import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";
import { ThemeProvider } from "~/components/theme-provider";
import Header from "~/components/header";
import type { Route } from "~/lib/types";
import { headers } from "next/headers";
import { auth } from "~/auth/server";
import UppyProvider from "~/components/upload/uppy-provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const routes: Route[] = [
  {
    name: "Explore",
    path: "/",
  },
  {
    name: "Recipes",
    path: "/recipes",
  },
];

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth.api.getSession({ headers: await headers() });
  return (
    <html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
      <body>
        <TRPCReactProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <UppyProvider>
              <header className="bg-background sticky top-0 z-50 px-3">
                <Header routes={routes} user={session?.user} />
              </header>
              {children}
            </UppyProvider>
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
