CREATE TABLE "odysseat_comment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "odysseat_comment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"recipeId" integer NOT NULL,
	"content" text NOT NULL,
	"rating" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "odysseat_recipe" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "odysseat_recipe_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"title" text NOT NULL,
	"content" text NOT NULL,
	"thumbnailUrl" varchar(1024),
	"position" point NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "odysseat_account" (
	"id" text PRIMARY KEY,
	"accountId" text NOT NULL,
	"providerId" text NOT NULL,
	"userId" text NOT NULL,
	"accessToken" text,
	"refreshToken" text,
	"idToken" text,
	"accessTokenExpiresAt" timestamp,
	"refreshTokenExpiresAt" timestamp,
	"scope" text,
	"password" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "odysseat_session" (
	"id" text PRIMARY KEY,
	"expiresAt" timestamp NOT NULL,
	"token" text NOT NULL UNIQUE,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL,
	"ipAddress" text,
	"userAgent" text,
	"userId" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "odysseat_user" (
	"id" text PRIMARY KEY,
	"name" text NOT NULL,
	"email" text NOT NULL UNIQUE,
	"emailVerified" boolean DEFAULT false NOT NULL,
	"image" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"username" text UNIQUE,
	"displayUsername" text,
	"role" text DEFAULT 'user' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "odysseat_verification" (
	"id" text PRIMARY KEY,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expiresAt" timestamp NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "account_userId_idx" ON "odysseat_account" ("userId");--> statement-breakpoint
CREATE INDEX "session_userId_idx" ON "odysseat_session" ("userId");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "odysseat_verification" ("identifier");--> statement-breakpoint
ALTER TABLE "odysseat_comment" ADD CONSTRAINT "odysseat_comment_userId_odysseat_user_id_fkey" FOREIGN KEY ("userId") REFERENCES "odysseat_user"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "odysseat_comment" ADD CONSTRAINT "odysseat_comment_recipeId_odysseat_recipe_id_fkey" FOREIGN KEY ("recipeId") REFERENCES "odysseat_recipe"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "odysseat_recipe" ADD CONSTRAINT "odysseat_recipe_userId_odysseat_user_id_fkey" FOREIGN KEY ("userId") REFERENCES "odysseat_user"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "odysseat_account" ADD CONSTRAINT "odysseat_account_userId_odysseat_user_id_fkey" FOREIGN KEY ("userId") REFERENCES "odysseat_user"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "odysseat_session" ADD CONSTRAINT "odysseat_session_userId_odysseat_user_id_fkey" FOREIGN KEY ("userId") REFERENCES "odysseat_user"("id") ON DELETE CASCADE;