CREATE TABLE "odysseat_account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "odysseat_session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "odysseat_session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "odysseat_user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "odysseat_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "odysseat_verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "odysseat_marker" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "odysseat_marker_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"description" text,
	"longitude" numeric(10, 7) NOT NULL,
	"latitude" numeric(10, 7) NOT NULL,
	"rating" numeric(3, 2),
	"imageUrl" varchar(1024),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "odysseat_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "odysseat_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "odysseat_account" ADD CONSTRAINT "odysseat_account_user_id_odysseat_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."odysseat_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "odysseat_session" ADD CONSTRAINT "odysseat_session_user_id_odysseat_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."odysseat_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "location_idx" ON "odysseat_marker" USING btree ("longitude","latitude");--> statement-breakpoint
CREATE INDEX "title_idx" ON "odysseat_marker" USING btree ("title");--> statement-breakpoint
CREATE INDEX "created_at_idx" ON "odysseat_marker" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "name_idx" ON "odysseat_post" USING btree ("name");